# Generated by Django 4.2.5 on 2023-10-01 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='birthdate',
        ),
        migrations.RemoveField(
            model_name='person',
            name='email',
        ),
    ]
