# Generated by Django 4.2.5 on 2023-10-01 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0002_remove_person_birthdate_remove_person_email'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Person',
            new_name='User',
        ),
    ]
