# Generated by Django 4.2.5 on 2023-10-01 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0003_rename_person_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='field2',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
