# Generated by Django 4.2.5 on 2023-10-01 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0004_user_field2'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='field3',
            field=models.CharField(default=5, max_length=30),
            preserve_default=False,
        ),
    ]
