# Generated by Django 4.2.5 on 2023-10-01 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0005_user_field3'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='field2',
        ),
        migrations.RemoveField(
            model_name='user',
            name='field3',
        ),
    ]
