# Generated by Django 4.2.5 on 2023-10-02 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0009_rename_user_appuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(default=None, max_length=30)),
                ('address_line_1', models.CharField(default=None, max_length=30)),
                ('address_line_2', models.CharField(default=None, max_length=30)),
                ('state', models.CharField(default=None, max_length=30)),
                ('city', models.CharField(default=None, max_length=30)),
                ('pincode', models.CharField(default=None, max_length=6)),
                ('type', models.CharField(default=None, max_length=4)),
                ('starting_date', models.DateField(blank=True, default=None, null=True)),
                ('ending_date', models.DateField(blank=True, default=None, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=12, null=True)),
                ('facilities', models.CharField(default=None, max_length=20)),
            ],
        ),
    ]
