# Generated by Django 4.2.5 on 2023-10-02 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0010_property'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='address_line_2',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
