# Generated by Django 4.2.5 on 2023-10-14 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0011_alter_property_address_line_2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property_Transfer_Contract',
            fields=[
                ('contract_id', models.AutoField(primary_key=True, serialize=False)),
                ('property_id', models.DecimalField(decimal_places=0, default=False, max_digits=10)),
                ('buyer', models.CharField(default=False, max_length=30)),
                ('first_name_buyer', models.CharField(default=None, max_length=30)),
                ('second_name_buyer', models.CharField(default=None, max_length=30)),
                ('seller', models.CharField(default=False, max_length=30)),
                ('first_name_seller', models.CharField(default=None, max_length=30)),
                ('second_name_seller', models.CharField(default=None, max_length=30)),
                ('price', models.DecimalField(decimal_places=0, default=False, max_digits=10)),
                ('date_of_contract', models.DateField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='RentalsContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_id', models.DecimalField(decimal_places=0, default=False, max_digits=10)),
                ('party_user_name', models.CharField(default=False, max_length=30)),
                ('first_name', models.CharField(default=None, max_length=30)),
                ('second_name', models.CharField(default=None, max_length=30)),
                ('party_type', models.CharField(default=False, max_length=1)),
                ('property_id', models.DecimalField(decimal_places=0, default=False, max_digits=10)),
                ('duration', models.DecimalField(decimal_places=0, default=False, max_digits=4)),
                ('price', models.DecimalField(decimal_places=0, default=False, max_digits=7)),
                ('date_of_contract', models.DateField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='appuser',
            name='balance',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='appuser',
            name='public_key',
            field=models.CharField(blank=True, default=None, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=10, null=True),
        ),
    ]
