# Generated by Django 4.2.5 on 2023-10-14 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0012_property_transfer_contract_rentalscontract_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyApplications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_id', models.DecimalField(decimal_places=0, default=False, max_digits=10)),
                ('interested_user', models.CharField(default=False, max_length=30)),
                ('status', models.CharField(default='PENDING', max_length=15)),
            ],
        ),
    ]
