# Generated by Django 4.2.5 on 2023-10-14 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0013_propertyapplications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='password',
            field=models.CharField(default=None, max_length=256),
        ),
    ]
