# Generated by Django 4.2.5 on 2023-10-15 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0015_property_lessee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='lessee',
        ),
    ]
