# Generated by Django 4.2.5 on 2023-10-26 12:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0017_appuser_dv'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='ending_date',
        ),
        migrations.RemoveField(
            model_name='property',
            name='starting_date',
        ),
        migrations.AddField(
            model_name='property',
            name='duration',
            field=models.DecimalField(blank=True, decimal_places=0, default=None, max_digits=3, null=True, validators=[django.core.validators.MaxValueValidator(limit_value=240)]),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='public_key',
            field=models.CharField(blank=True, default=None, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='rentalscontract',
            name='duration',
            field=models.DecimalField(decimal_places=0, default=False, max_digits=3),
        ),
    ]
