# Generated by Django 4.2.5 on 2023-10-26 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0018_remove_property_ending_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property_transfer_contract',
            name='property_address_line_1',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AddField(
            model_name='property_transfer_contract',
            name='property_address_line_2',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='property_transfer_contract',
            name='property_city',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AddField(
            model_name='property_transfer_contract',
            name='property_pincode',
            field=models.CharField(default=None, max_length=6),
        ),
        migrations.AddField(
            model_name='property_transfer_contract',
            name='property_state',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AddField(
            model_name='property_transfer_contract',
            name='signature',
            field=models.CharField(default=False, max_length=512),
        ),
    ]
