# Generated by Django 4.2.5 on 2023-10-26 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0020_alter_property_transfer_contract_signature'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property_transfer_contract',
            old_name='contract_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='property_transfer_contract',
            old_name='signature',
            new_name='token',
        ),
        migrations.AddField(
            model_name='property_transfer_contract',
            name='application_id',
            field=models.DecimalField(decimal_places=0, default=None, max_digits=10),
        ),
        migrations.AlterField(
            model_name='property_transfer_contract',
            name='buyer',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AlterField(
            model_name='property_transfer_contract',
            name='date_of_contract',
            field=models.DateField(default=None),
        ),
        migrations.AlterField(
            model_name='property_transfer_contract',
            name='price',
            field=models.DecimalField(decimal_places=0, default=None, max_digits=10),
        ),
        migrations.AlterField(
            model_name='property_transfer_contract',
            name='property_id',
            field=models.DecimalField(decimal_places=0, default=None, max_digits=10),
        ),
        migrations.AlterField(
            model_name='property_transfer_contract',
            name='seller',
            field=models.CharField(default=None, max_length=30),
        ),
    ]
