# Generated by Django 4.2.5 on 2023-10-26 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0021_rename_contract_id_property_transfer_contract_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property_transfer_contract',
            name='token',
            field=models.CharField(default=None, max_length=2000),
        ),
    ]
