# Generated by Django 4.2.5 on 2023-10-26 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0022_alter_property_transfer_contract_token'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property_transfer_contract',
            old_name='date_of_contract',
            new_name='date_of_agreement',
        ),
    ]
