# Generated by Django 4.2.5 on 2023-10-31 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0023_rename_date_of_contract_property_transfer_contract_date_of_agreement'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyapplications',
            name='property_owner',
            field=models.CharField(default=False, max_length=30),
        ),
    ]
