# Generated by Django 4.2.5 on 2023-10-31 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0024_propertyapplications_property_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyapplications',
            name='application_type',
            field=models.CharField(default=False, max_length=4),
        ),
    ]
