# Generated by Django 4.2.5 on 2023-10-31 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0025_propertyapplications_application_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rentalscontract',
            old_name='contract_id',
            new_name='application_id',
        ),
        migrations.RenameField(
            model_name='rentalscontract',
            old_name='date_of_contract',
            new_name='date_of_agreement',
        ),
        migrations.RenameField(
            model_name='rentalscontract',
            old_name='price',
            new_name='rent_per_month',
        ),
        migrations.RenameField(
            model_name='rentalscontract',
            old_name='party_user_name',
            new_name='username',
        ),
        migrations.AddField(
            model_name='rentalscontract',
            name='property_address_line_1',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AddField(
            model_name='rentalscontract',
            name='property_address_line_2',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='rentalscontract',
            name='property_city',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AddField(
            model_name='rentalscontract',
            name='property_pincode',
            field=models.CharField(default=None, max_length=6),
        ),
        migrations.AddField(
            model_name='rentalscontract',
            name='property_state',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AddField(
            model_name='rentalscontract',
            name='total_rent',
            field=models.DecimalField(decimal_places=0, default=False, max_digits=11),
        ),
        migrations.AlterField(
            model_name='rentalscontract',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
