# Generated by Django 4.2.5 on 2023-10-31 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0026_rename_contract_id_rentalscontract_application_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalscontract',
            name='token',
            field=models.CharField(default=None, max_length=2000),
        ),
    ]
