# Generated by Django 4.2.5 on 2023-11-03 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0028_alter_rentalscontract_party_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('user', models.CharField(default=None, max_length=30, primary_key=True, serialize=False)),
                ('otp', models.CharField(max_length=6)),
                ('expiry_time', models.DateTimeField()),
                ('valid', models.BooleanField()),
            ],
        ),
    ]
