# Generated by Django 4.2.5 on 2023-11-11 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0029_otp'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportedBuyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_id', models.DecimalField(decimal_places=0, default=False, max_digits=10)),
                ('buyer', models.CharField(default=False, max_length=30)),
                ('seller', models.CharField(default=False, max_length=30)),
            ],
        ),
    ]
