# Generated by Django 4.2.5 on 2023-11-12 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0030_reportedbuyer'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportedListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_id', models.DecimalField(decimal_places=0, default=False, max_digits=10)),
                ('reporter', models.CharField(default=False, max_length=30)),
            ],
        ),
    ]
