# Generated by Django 4.2.5 on 2023-11-12 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0031_reportedlisting'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportedlisting',
            name='complain_id',
            field=models.DecimalField(decimal_places=0, default=False, max_digits=1),
        ),
    ]
