# Generated by Django 4.2.5 on 2023-11-13 18:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0032_reportedlisting_complain_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='first_name',
            field=models.CharField(default=None, max_length=30, validators=[django.core.validators.MaxLengthValidator(limit_value=30, message='First name must be at most 30 characters.')]),
        ),
    ]
